#   YT_DLP_VERSION="$(URL="$(curl --head https://github.com/yt-dlp/yt-dlp/releases/latest --output /dev/null --silent --write-out '%{redirect_url}')"; printf '%s' "${URL##*/}")"
ARG YT_DLP_VERSION
#   DENO_VERSION="$(TOKEN="$(curl 'https://dhi.io/token?scope=repository:deno:pull&service=registry.docker.io' --user "$USER_PASS" | jq --raw-output '.token')"; VERSION_FULL="$(curl https://dhi.io/v2/deno/manifests/1 -H "Authorization: Bearer $TOKEN" -H 'Accept: application/vnd.oci.image.index.v1+json' | jq --raw-output '.annotations["org.opencontainers.image.version"]')"; printf '%s' "${VERSION_FULL%%-*}")"
ARG DENO_VERSION
#   YT_DLP_FFMPEG_VERSION="$(URL="$(curl 'https://github.com/yt-dlp/FFmpeg-Builds/releases?q=-tag:latest' --silent | grep -E --max-count=1 --only-matching 'https://github.com/yt-dlp/FFmpeg-Builds/releases/expanded_assets/[^"]+')"; printf '%s' "${URL##*/}")"
ARG YT_DLP_FFMPEG_VERSION

FROM dhi.io/debian-base:trixie AS builder
ARG TARGETPLATFORM
ARG YT_DLP_VERSION
ARG YT_DLP_FFMPEG_VERSION

RUN --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var/lib/apt/lists \
    apt-get update \
 && apt-get --no-install-recommends --no-install-suggests -y install \
      wget \
      xz-utils \
 && case "$TARGETPLATFORM" in \
      "linux/amd64") \
        YT_DLP_FFMPEG_VARIANT='linux64' \
        YT_DLP_VARIANT='linux' \
        ;; \
      "linux/arm64") \
        YT_DLP_FFMPEG_VARIANT='linuxarm64' \
        YT_DLP_VARIANT='linux_aarch64' \
        ;; \
    esac \
 && URL_PATH="$(wget "https://github.com/yt-dlp/FFmpeg-Builds/releases/expanded_assets/$YT_DLP_FFMPEG_VERSION" --output-document - | grep -E --only-matching '/yt-dlp/FFmpeg-Builds/releases/download/[^/"]+/ffmpeg-[^-"]+-[^-"]+-[^-"]+-'"$YT_DLP_FFMPEG_VARIANT"'-gpl.tar.xz')" \
 && wget --directory-prefix /tmp --progress dot:giga "https://github.com$URL_PATH" \
 && tar --extract --file /tmp/ffmpeg-*.tar.xz --no-same-owner --exclude 'ffmpeg-*/bin/ffplay' --exclude 'ffmpeg-*/doc' --exclude 'ffmpeg-*/man' --directory /opt --verbose \
 && ln -s --verbose --target-directory /usr/local/bin /opt/ffmpeg-*/bin/* \
 && wget --directory-prefix /opt --progress dot:giga "https://github.com/yt-dlp/yt-dlp/releases/download/$YT_DLP_VERSION/yt-dlp_$YT_DLP_VARIANT" \
 && chmod --verbose +x /opt/yt-dlp_* \
 && ln -s --verbose /opt/yt-dlp_* /usr/local/bin/yt-dlp \
 && DEBIAN_FRONTEND=noninteractive apt-get --auto-remove -y purge \
      wget \
      xz-utils \
 && apt-get clean \
 && mkdir -p --verbose /home/deno/.cache /home/yt-dlp \
 && chown -R --verbose 1993:1993 /home/deno/.cache /home/yt-dlp


FROM dhi.io/deno:$DENO_VERSION

COPY --from=builder --parents /opt/ffmpeg-* /opt/yt-dlp_* /usr/local/bin/ffmpeg /usr/local/bin/yt-dlp /home/deno/.cache /home/yt-dlp /

WORKDIR /home/deno

RUN [ "/usr/local/bin/deno", "run", "-A", "--reload", "jsr:@deno/installer-shell-setup/bundled", "/home/deno/.deno" ]

VOLUME /home/deno/.cache/yt-dlp
VOLUME /home/yt-dlp/temp
VOLUME /home/yt-dlp/home

WORKDIR /home/yt-dlp/home

ENTRYPOINT [ "/usr/local/bin/yt-dlp" ]
